### ISSUE TITLE
magic command %%

### ISSUE THREAD

**Issue by flashpixx** [janpfeifer/gonb#128]
Hello,

Is it possible that the go code can be executed without `%%`, it makes it easier to write a complex notebook with multiple cells. so I can do the gi imports in a cell, and than execute some go elements cell by cell.

Thanks

**Comment by janpfeifer** [comment]
hi @flashpixx,

Yes, it's supposed to work as you describe -- I build my larger notebooks in the same fashion you described.

A quick trivial example:

![image](https://github.com/user-attachments/assets/a2688ca4-413c-42d3-bc35-54a22365fa8f)

But pls let me know if you are finding any problems -- there may be cases that are not well covered.

cheers

**Comment by flashpixx** [comment]
you see in your cell 3, that you have to add `%%` is it possible to remove this magic command per default? I missed it multiple times, but than it creates an error. So it would be nice if it works without `%%`

**Comment by janpfeifer** [comment]
Oh, sorry I misunderstood.

So a couple of things to understand about `gonb` that may not work the way you want -- but mostly you can get it to work slightly differently:

1. `gonb` just puts together the contents from each input cell and merge with previous content, replacing the `main` function, recompile and execute. So, while declarations (imports, variables, types, constants) are carried over from cell to cell, the result of operations are not -- each time, it's executed from scratch. These has advantages (all is compiled -- as opposed to interpreted, it's standard Go -- so CGO stuff links and works) and disadvantages, the obvious one, it doesn't work like a python/interpreter REPL. See the [github.com/janpfeifer/gonb/cache](https://pkg.go.dev/github.com/janpfeifer/gonb/cache), for a simple/quick way to save/quickly restore computations that take time.
2. If (1) is not an issue for you -- or if the work around suffice -- then there is still the extra annoyance of using `%%` to indicate that things should go to the `main` function (notice you can also define the lines to execute inside a `func main() {...}`). The problem here is that I haven't written a modified parser of  Go code: I use the standard Go parser to parse the cell contents, and it doesn't accept statements in the global scope -- statement must go inside function declarations. It would indeed be nice if I could parse and automatically stick every statement inside the `main` function -- although it would cause ambiguity with the variables/constants and types: were they meant to go inside main or in the global scope. But I suspect that is not your issue, but rather it is (1).

In any case, I tried to explain all these in the tutorial. But let me know if you have any other questions. Or if you have any other ideas of how to make it work.

Let me just add: adjusting to the issue in (1) is not a big problem, once you get used to it. Just write all your partial commands in a function, and always call it inside the %%. This way you can keep composing parts in multiple functions. At least I've been doing this is [some large notebooks (see examples section)](https://github.com/gomlx/gomlx) and it never bothered me (I used to also use colab/python notebooks before).

**Comment by flashpixx** [comment]
Hi,

I'm working some years in Golang, so I know how a Go programm is working on a default behaviour. So with 1 I'm fine, because I see this on error messages that GoNB creates a temporary file and execute it.

I didn't understand it in detail, can you explain it to me or point me to your code liens? Maybe I can take a look and think about it. I see GoNB as a good work also for some Go beginners, but if you come form the Python world it could be a better idea that it works in the same way. With 1 I'm fine, but maybe I can take a look on 2 and improve it.

**Comment by janpfeifer** [comment]
Nice, that's good to know that it's not (1) the issue. 

About (2): can you write up a simple example of what you would expect it to work ? (even if only a couple of cells, a couple of lines)

The main part of `gonb` that parses the code is in [parser.go:125 - State.parseFromGoCode](https://github.com/janpfeifer/gonb/blob/main/internal/goexec/parser.go#L125).

Let me now if have any questions.

If you want to add some "`printf`" to the code, just use `klog.Infof("some debug message: %s", str)`, and see the output in JupyterLab output. Or install `gonb --install --extra_log=/tmp/gonb.out` and it will also output logs to `/tmp/gonb.out`.

Or, for much more detail, how I usually run it when developing, I go to where I cloned the `gonb` repository and do:

```
go run . --install --logtostderr --vmodule=goexec=2,specialcmd=2,cellmagic=2,gopls=2,connection=2,kernel=2,dispatcher=2 --extra_log=/tmp/gonb.out
```

The first time you do this, it will require restarting `jupyter-lab` (the `gonb` binary will be in a different location, and there are new command line options). After that, after recompiling `gonb`, you just need to restart the kernel (can be done from the browser).

**Comment by janpfeifer** [comment]
Actually, I should also point you to `State.parseLinesAndComposeMain()`, in the same file `parser.go`, line 398. 
It receives the cell contents, call `State.createGoFileFromLines` to create the Go file (including converting `%%` to a `func main() {...}` .

**Comment by janpfeifer** [comment]
I'm closing the issue for now. But feel free to reopen it if there is something else.
