### ISSUE TITLE
Function to trigger downloads from cells data

### ISSUE THREAD

**Issue by oderwat** [janpfeifer/gonb#134]
Hello @janpfeifer,

I just created a function that lets you send data generated in a cell as download. Maybe you want to add this somewere in your accompanion packages?

```go
import "github.com/janpfeifer/gonb/gonbui/dom"

func Download(fileName string, data []byte, mimeType string) error {
    var b bytes.Buffer
    w := base64.NewEncoder(base64.StdEncoding, &b)
    if _, err := w.Write(data); err != nil {
    	return err
    }
    if err := w.Close(); err != nil {
        return err
    }
    dataURL:="data:"+mimeType+";base64,"+b.String()
    
    dom.TransientJavascript(`var downloadLink = document.createElement('a');
downloadLink.href = '`+dataURL+`';
downloadLink.download = '`+fileName+`';
document.body.appendChild(downloadLink);
downloadLink.click();
document.body.removeChild(downloadLink);`)
    return nil
}

func MustDownload(fileName string, data []byte, mimeType string) {
    err := Download(fileName, data, mimeType)
    if err != nil {
        panic(err)
    }
}

%%
MustDownload("example.txt", []byte("This is an example!"), "application/octet-stream")
```

**Comment by janpfeifer** [comment]
What a great idea!

A couple of suggestions:

-  Including it in `gonbui/dom` package. I first thought of `gonbui` itself, but that would create a circular dependency (generally, dependencies go from specific to generic packages, except for packages that define interfaces and types).
- Rename it to `BrowserDownload`: because "download" is very ambiguous about the direction of the data transfer, and I would assume a `Download` function would transfer something from the internet to the running cell code (in the remote machine where the kernel runs) .

What do you think ? With the suggestions, plus documentation and an example, it would [look like this (in a branch named "download')](https://github.com/janpfeifer/gonb/blob/download/gonbui/dom/download.go)

**Comment by janpfeifer** [comment]
Another thought I had: `bytes.Buffer` never returns an error (Go panics if out-of-memory). So `BrowserDownload` (?) also doesn't need to return one.

**Comment by oderwat** [comment]
@janpfeifer Looks good to me. The original routine created data and could fail. You are right about the oom.

**Comment by oderwat** [comment]
Maybe `SendFileAsDownload()` is better though. "BrowserDownload" sounds like we download a browser tbh. Naming things is had :)

**Comment by oderwat** [comment]
Thank you too!
