### ISSUE TITLE
A way to get the output of a cell?

### ISSUE THREAD

**Issue by oderwat** [janpfeifer/gonb#142]
I think `%%writefile` allows to write the cell and optionally the result into a file. But I would like to be able to get the result of the cell in a string (for downloading or saving it). Is that even possible?

**Comment by janpfeifer** [comment]
A few similar functionality to that -- probably not what you want, but just to make sure it doesn't already fits the use-case:

1. One can always redirect the output in Go of course, and use the new `dom.SendAsDownload` that you suggested in another issue. (Adding here in case someone else bumps into this issue).
2. Run and export the whole notebook to text. The `cmd/nbexec` does that (using Jupyter's `nbconvert`) for tests. But the output is the whole notebook coonverted to text (I think it would be easy to user HTML).
3. Manual copy&paste for simple cases, one-of.

Now generically, I wonder if JupyterLab has a plugin for that ? Since this is something that presumably is kernel independent.

Implementing this in GoNB should be possible ... This comes to mind:

1. How to expose the functionality in GoNB ? Maybe a special command like `%capture <output_file>`. Then all the output of the cell execution is also saved in the given file ?
2. How to handle outputs from different mime-types / stdout / stderr, given the `<output_file>` extension ? If feels there should be some conversion somewhere.
3. Or do you envision the special command to be issued after the cell is executed ? Something like `%capture <cell#> <output_file>` ? In which case GoNB would have to constantly preserve all outputs of all cells (or up to a certain amount of memory) 

Any thoughts ?

**Comment by oderwat** [comment]
I just want the output of a single cell and be able to work with that in the next cells. If that could be captured into a file that would be great. I would like to get the "exact" data as sent into the "result" (presuming that this will be HTML). The file could then be read and for example converted into a PDF and make it downloadable.

**Comment by oderwat** [comment]
> 1. One can always redirect the output in Go of course, and use the new `dom.SendAsDownload` that you suggested in another issue. (Adding here in case someone else bumps into this issue).

This would mean that one needs to clone all the gonbui functionality and have doubled code at many places.

**Comment by janpfeifer** [comment]
Btw, do you know before running the cell, that you want to save its output ? Or is it cheap to re-run the cell ?
Meaning, would the idea of having a special `%capture <output_file>` in the cell you want to capture work ?

**Comment by oderwat** [comment]
I do know upfront that I want to save it.

**Comment by janpfeifer** [comment]
So I think I got this to work. But before I merge the PR to `main`, would check out if the functionality looks right ? This is the notebook I use to test the new `%capure [-a] <file>` special command:

https://github.com/janpfeifer/gonb/blob/capture/examples/tests/capture.ipynb

**Comment by oderwat** [comment]
I think this is great, but I do not like the log line. Either let me specify "-q" for being quiet or just remove it. There is also a double // in the file path.

**Comment by janpfeifer** [comment]
Done: i simply removed the log line (and fixed the double "/").

**Comment by janpfeifer** [comment]
Included in the v0.10.6 release, also already included in the new docker (`janpfeifer/gonb_jupyterlab:v0.10.6` or `janpfeifer/gonb_jupyterlab:latest`)
