### ISSUE TITLE
Tabs are added to raw strings

### ISSUE THREAD

**Issue by AnotherCodeArtist** [janpfeifer/gonb#19]
Hi Jan!

Looks like your are using some code beautifier behind the scenes? This has some unwanted aspects on raw strings. Here's an example:

```go
result := 
`This is some text!
It is stored in a file!
Every file needs to have an end.
`
fmt.Println(result)
```

This produces:
```
This is some text!
	It is stored in a file!
	Every file needs to have an end.
```

Any idea how to fix this?

**Comment by janpfeifer** [comment]
You are right! Everything after `%%` is moved inside a `func main() { ... }` with each line indented ...

So short-term solutions:

1. Remove the `%%` and create your own `func main() {...}` for your particular cell. Or move 
2. Or move the statement `result := ...` to a global variable, if you don't mind it being around for the other cells.

Longer-term solution:

1. Should we remove the indenting when converting stuff after `%%`  ? It should be simple enough ... but I wonder ...
2. Actually parsing and understanding the Go code, and when the line is inside a string, not indenting it: this would be the
optimal solution, but it's complicated, since we would have to actually parse the code ourselves and understand much more about it, which I wanted to avoid, to keep it simple.

Any thoughts ?

**Comment by AnotherCodeArtist** [comment]
Hi Jan!

Since the solution is just about using `func main()` explicitly that's absolutely fine with me.

**Comment by janpfeifer** [comment]
I'll leave it as is for now then.
