### ISSUE TITLE
Not working in VSCode

### ISSUE THREAD

**Issue by JCzz** [janpfeifer/gonb#20]
Hi

Just installed on Mac M1 and vscode [jupyter noodbook from Microsoft](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter). I get:

```
expected declaration, found Hello
in goexec.ExecuteCell(): parsing go files in TempDir "[/var/folders/ws/r3lmtqdj03d3jn5l3v3t_s3w0000gn/T/gonb_0acd825](https://file+.vscode-resource.vscode-cdn.net/var/folders/ws/r3lmtqdj03d3jn5l3v3t_s3w0000gn/T/gonb_0acd825a)
```

From this code
```
import "fmt"

func Hello(){
    fmt.Println("hello world!")
}

Hello()
```

**Comment by janpfeifer** [comment]
hi @JCzz , I'm sorry to hear about the issue.

I think the issue is that you cannot have in Go a statement (function call) like `Hello()` outside of a function. So you need to move it inside the `func main()`, which you can do in two ways in GoNB. 

1. The usual way:

```
import "fmt"

func Hello(){
    fmt.Println("hello world!")
}

func main() {
  Hello()
}
```

2. GoNB introduces a shortcut to `func main()` so one doesn't need to write it every time. Use `%%` and everything after will be put inside a `func main` automatically:

```
import "fmt"

func Hello(){
    fmt.Println("hello world!")
}

%%
Hello()
```

Let me know if that works for you.

Btw, in JupyterLab the error looks a bit different (It adds a context where in the cell the error is, and something you can mouse-over). On the weekend I'll check if I can improve the VSCode experience.

**Comment by JCzz** [comment]
Thanks @janpfeifer

This is very cool, I absolutely love it - thanks for clearing it up for me!

/Christian
