### ISSUE TITLE
Cannot handle go 1.21.0 work files

### ISSUE THREAD

**Issue by bagel897** [janpfeifer/gonb#53]
goExec.AutoTrack failed: /tmp/gonb_e5d525c9/go.work:1: invalid go version '1.21.0': must match format 1.23

**Comment by janpfeifer** [comment]
Thanks for the report, let me take a look into it before I cut the new release (v0.7.8).

**Comment by janpfeifer** [comment]
This seems to be related to lack of "forward" compatibility of the go.mod parsing tools, and was fixed with me updating the dependencies of GoNB to the newer version of the parser.

More in:

https://github.com/golang/go/issues/61851

PR coming soon, I'm also adding a test to the `go.work` framework.

**Comment by janpfeifer** [comment]
It's submitted and released. Here the problem went away, so closing the issue for now.

But let me know if you notice anything!

cheers
